# Generated by Django 2.2 on 2020-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_company', models.CharField(max_length=150, verbose_name='Nome da empres:')),
                ('company_picture', models.ImageField(blank=True, null=True, upload_to='img/author/', verbose_name='Logo da empresa')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
